# Generated by Django 2.1.5 on 2019-12-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('visitas', models.IntegerField(default=0)),
                ('mon', models.BooleanField(default=True)),
                ('mon_open', models.CharField(max_length=20, null=True)),
                ('mon_close', models.CharField(max_length=20, null=True)),
                ('tue', models.BooleanField(default=True)),
                ('tue_open', models.CharField(max_length=20, null=True)),
                ('tue_close', models.CharField(max_length=20, null=True)),
                ('wed', models.BooleanField(default=True)),
                ('wed_open', models.CharField(max_length=20, null=True)),
                ('wed_close', models.CharField(max_length=20, null=True)),
                ('thu', models.BooleanField(default=True)),
                ('thu_open', models.CharField(max_length=20, null=True)),
                ('thu_close', models.CharField(max_length=20, null=True)),
                ('fri', models.BooleanField(default=True)),
                ('fri_open', models.CharField(max_length=20, null=True)),
                ('fri_close', models.CharField(max_length=20, null=True)),
                ('sat', models.BooleanField(default=True)),
                ('sat_open', models.CharField(max_length=20, null=True)),
                ('sat_close', models.CharField(max_length=20, null=True)),
                ('sun', models.BooleanField(default=True)),
                ('sun_open', models.CharField(max_length=20, null=True)),
                ('sun_close', models.CharField(max_length=20, null=True)),
                ('photo1', models.FileField(upload_to='uploads/')),
                ('photo2', models.FileField(upload_to='uploads/')),
                ('photo3', models.FileField(upload_to='uploads/')),
                ('photo4', models.FileField(upload_to='uploads/')),
                ('photo5', models.FileField(upload_to='uploads/')),
                ('localizacao', models.TextField(null=True)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=3, max_digits=8)),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('twitter', models.CharField(max_length=255, null=True)),
                ('linkedin', models.CharField(max_length=255, null=True)),
                ('instagram', models.CharField(max_length=255, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Company')),
            ],
        ),
    ]
