# Generated by Django 2.1.5 on 2020-01-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200102_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desconto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
