# Generated by Django 2.1.5 on 2020-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_company_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='company',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='company',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='company',
            name='visitas',
        ),
        migrations.AddField(
            model_name='company',
            name='photo_yelp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rating_yelp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
