# Generated by Django 2.1.5 on 2020-01-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200102_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link_yelp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
