# Generated by Django 2.1.5 on 2020-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_company_link_yelp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='link_yelp',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
